mybatis:
    type-aliases-package: cn.edu.ccut.bo
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jwang
        username: root
        password: root
    thymeleaf: 
        suffix: .html