server: 
    port: 8080
management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application: 
        name: springboot-test
    boot:
        admin:
            client:
                url: http://localhost:8888